<style>
ul.packagistRow a {
    color: black;
	font: Tahoma 20px bold;
}
ul.packagistRow {
    position: relative;
    list-style: none;
    display: block;
    float: left;
    width: 205px;
	background-color: #efefaa;
	min-height: 150px;
	padding: 5px;
	margin: 5px;
}
.packagistDownloads {
    position: absolute;
	top: 130px;
	left: 180px;
}
.packagistFavers {
    position: absolute;
	top: 130px;
	left: 10px;
}
</style>
<div>
<h1>Packagist Demo</h1>

<?php echo $this->packagist()->search(array('q' => 'packagist')); ?>
<div style="clear: both;">&nbsp;</div>
</div>