language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer install --verbose
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml --verbose --coverage-text --configuration tests/

after_script:
  - php vendor/bin/coveralls
