language: php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --dev --no-interaction
  - mkdir -p build/logs

script:
  - cd test
  - phpunit --coverage-clover build/logs/clover.xml
  - cd ..

after_script:
  - php vendor/bin/coveralls
